Models/Pager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Pager
    {
        public int TotalItem { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }

        public string Action { get; set; }
        public string SearchText { get; set; }
        public string SortExpression { get; set; }

        //public Pager() { }

        public Pager(int totalItems, int currentPage, int pageSize = 5)
        {
            TotalItem = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;

            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            TotalPages = totalPages;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            if (TotalItem == 0)
            {
                StartPage = 0;
                CurrentPage = 0;
            }
            else
            {
                StartPage = startPage;
                EndPage = endPage;
            }
        }
    }
}

Controllers/ActorController.cs
using Cinema.Data;
using Cinema.Models;
using Cinema.Repository.Interfaces;
using Cinema.Tools;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    //[Authorize]
    public class ActorController : Controller
    {

        private readonly IActor _service;

        public ActorController(IActor service)
        {
            _service = service;
        }

        //private SortModel ApplySort(string sortExpression)
        //{
        //    ViewData["SortParamFullName"] = "fullname";
        //    ViewData["SortParamBio"] = "biografy";
        //    ViewData["SortIconFullName"] = "";
        //    ViewData["SortIconBio"] = "";


        //    SortModel sortModel = new SortModel();

        //    switch (sortExpression.ToLower())
        //    {
        //        case "fullname_desc":
        //            sortModel.SortedOrder = SortOrder.Descending;
        //            sortModel.SortedProperty = "fullname";
        //            ViewData["SortIconFullName"] = "bi bi-file-arrow-up-fill";
        //            ViewData["SortParamFullName"] = "fullname";
        //            break;

        //        case "biografy":
        //            sortModel.SortedOrder = SortOrder.Ascending;
        //            sortModel.SortedProperty = "biografy";
        //            ViewData["SortIconBio"] = "bi bi-file-arrow-down-fill";
        //            ViewData["SortParamBio"] = "biografy_desc";
        //            break;
        //        case "biografy_desc":
        //            sortModel.SortedOrder = SortOrder.Descending;
        //            sortModel.SortedProperty = "biografy";
        //            ViewData["SortIconBio"] = "bi bi-file-arrow-up-fill";
        //            ViewData["SortParamBio"] = "biografy";
        //            break;
        //        default:
        //            sortModel.SortedOrder = SortOrder.Ascending;
        //            sortModel.SortedProperty = "fullname";
        //            ViewData["SortIconFullName"] = "bi bi-file-arrow-down-fill";
        //            ViewData["SortParamFullName"] = "fullname_desc";
        //            break;
        //    }

        //    return sortModel;
        //}



        public IActionResult Index(string sortExpression = "", string searchText = "", int pg = 1, int pageSize = 3)
        {
            //SortModel sortModel = ApplySort(sortExpression);

            PaginatedList<Actor> actors;

            SortModel sortModel = new SortModel();

            sortModel.AddColumn("fullname");
            sortModel.AddColumn("biografy");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;

            ViewBag.searchText = searchText;

            actors = _service.GetAll(sortModel.SortedProperty, sortModel.SortedOrder, searchText, pg, pageSize);

            //PaginatedList<Actor> retActor = new PaginatedList<Actor>(actors, pg, pageSize);

            //int totalRecords = ((PaginatedList<Actor>)actors).TotalRecords;

            var pager = new Pager(actors.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            ViewBag.Pager = pager;

            //actors = actors.Skip((pg - 1) * pageSize).Take(pageSize).ToList();

            //const int pageSize = 3;

            //if (pg < 1)
            //{
            //    pg = 1;
            //}

            //int recsCount = _service.GetAll().Count();

            //var pager = new Pager(recsCount, pg, pageSize);

            //int recSkip = (pg - 1) * pageSize;

            //actors = _service.GetAll().Skip(recSkip).Take(pager.PageSize).ToList();

            //ViewBag.Pager = pager;


            //List<Actor> actors = _service.GetAll(sortModel.SortedProperty, sortModel.SortedOrder);



            return View(actors);

            //return View(retActor);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            Actor actor = new Actor();

            return View(actor);
        }

        [HttpPost]
        public IActionResult Create(Actor actor)
        {
            try
            {
                _service.Add(actor);
            }
            catch
            {

            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int id)
        {
            Actor actor = _service.GetById(id);

            return View(actor);
        }

        public IActionResult Edit(int id)
        {
            Actor actor = _service.GetById(id);

            return View(actor);
        }

        [HttpPost]
        public IActionResult Edit(Actor actor)
        {
            try
            {
                _service.Update(actor);
            }
            catch
            {

            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Actor actor = _service.GetById(id);

            return View(actor);
        }

        [HttpPost]
        public IActionResult Delete(Actor actor)
        {
            try
            {
                _service.Delete(actor);
            }
            catch
            {

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/AdminController.cs
using Cinema.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    //[Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public AdminController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = _userManager.Users.OrderBy(x => x.UserName).ToList();

            return View(users);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = _roleManager.Roles.ToList();

            return View(roles);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModels model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await _roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListRoles");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId);

            ViewBag.roleName = role;

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await _userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                    {
                        continue;
                    }
                    else
                    {
                        return RedirectToAction("EditRole", new { Id = roleId });
                    }
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId = userId;

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var model = new List<RolesUserViewModel>();

            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new RolesUserViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }
                else
                {
                    userRolesViewModel.IsSelected = false;
                }

                model.Add(userRolesViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(List<RolesUserViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }

            result = await _userManager.AddToRolesAsync(user,
                model.Where(x => x.IsSelected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = userId });
        }


        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                Roles = userRoles
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {

Views/Shared/NotFound.cshtml
<div class="row mt-5">
    <div class="col-md-6 offset-3">
        <br />
        <br />
        <a class="btn btn-success offset-3" asp-controller="Admin" asp-action="ListUsers">Back</a>
        <br />
        <br />
        <h1 class="text-primary">Not Found... It's very...</h1>
        <hr />
        <br />
        <br />
        <img src="http://risovach.ru/upload/2014/08/mem/gugl-blya_57729440_orig_.jpeg" />
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Cinema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*@if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                            {*@
                        <li class="dropdown nav-item pr-2">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Admin" asp-action="Index">Admin</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Admin" asp-action="ListRoles">Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Admin" asp-action="ListUsers">Users</a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown nav-item pr-2">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                Manager
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Actor" asp-action="Index">Actors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Producer" asp-action="Index">Producers</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                                </li>
                            </ul>
                        </li>
                        @*}*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cinema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Pager.cshtml
@model Cinema.Models.Pager

<div class="container">
    <ul class="pagination justify-content-end">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-action="@Model.Action"
                   asp-route-pg="1"
                   asp-route-pageSize="@Model.PageSize"
                   asp-route-searchText="@Model.SearchText"
                   asp-route-sortExpression="@Model.SortExpression">
                    First
                </a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   asp-action="@Model.Action"
                   asp-route-pg="@(Model.CurrentPage - 1)"
                   asp-route-pageSize="@Model.PageSize"
                   asp-route-searchText="@Model.SearchText"
                   asp-route-sortExpression="@Model.SortExpression">
                    Previous
                </a>
            </li>
        }

        @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
        {
            <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                @if (pge != Model.CurrentPage)
                {
                    <a class="page-link"
                       asp-action="@Model.Action"
                       asp-route-pg="@pge"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-searchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        @pge
                    </a>
                }
                else
                {
                    <span class="page-link">@pge</span>
                }
            </li>
        }

        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-action="@Model.Action"
                   asp-route-pg="@(Model.CurrentPage + 1)"
                   asp-route-pageSize="@Model.PageSize"
                   asp-route-searchText="@Model.SearchText"
                   asp-route-sortExpression="@Model.SortExpression">
                    Next
                </a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   asp-action="@Model.Action"
                   asp-route-pg="@(Model.TotalPages)"
                   asp-route-pageSize="@Model.PageSize"
                   asp-route-searchText="@Model.SearchText"
                   asp-route-sortExpression="@Model.SortExpression">
                    Last
                </a>
            </li>
        }
    </ul>
</div>